=== YoAashutosh/Yukie-Gift-Card-Store/Development/catalog_20048803.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="yukie_store" type="yukie_storeType">
    <xs:annotation>
      <xs:documentation>Name: Aashutosh Sharma
    londonmetID: 20048803
    collegeID: np01cp4s210087
    description</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="storeType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="time_opening" minOccurs="0"/>
      <xs:element type="xs:string" name="time_closing" minOccurs="0"/>
      <xs:element type="xs:string" name="location" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="online" use="optional"/>
    <xs:attribute type="xs:string" name="physical" use="optional"/>
  </xs:complexType>
  <xs:complexType name="numberType">
    <xs:sequence>
      <xs:element type="xs:string" name="mobile_number"/>
      <xs:element type="xs:string" name="telephone_number"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="cardImgType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="img" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="voucher_physicalType">
    <xs:sequence>
      <xs:element type="voucher_forType" name="voucher_for"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="cardType">
    <xs:sequence>
      <xs:element type="cardImgType" name="cardImg"/>
      <xs:element type="categoryType" name="category"/>
      <xs:element type="voucher_onlineType" name="voucher_online" minOccurs="0"/>
      <xs:element type="voucher_physicalType" name="voucher_physical" minOccurs="0"/>
      <xs:element type="deliveryType" name="delivery" minOccurs="0"/>
      <xs:element type="delivery_chargeType" name="delivery_charge" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="kind" use="optional"/>
    <xs:attribute type="xs:string" name="C_id" use="optional"/>
  </xs:complexType>
  <xs:complexType name="deliveryType">
    <xs:sequence>
      <xs:element type="delivery_periodType" name="delivery_period"/>
      <xs:element type="delivery_period1Type" name="delivery_period1"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="type" use="optional"/>
  </xs:complexType>
  <xs:complexType name="delivery_chargeType">
    <xs:sequence>
      <xs:element type="delivery_meansType" name="delivery_means"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="delivery_meansType" mixed="true">
    <xs:sequence>
      <xs:element type="delivery_costType" name="delivery_cost" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="by_air" use="optional"/>
    <xs:attribute type="xs:string" name="by_train" use="optional"/>
    <xs:attribute type="xs:string" name="by_road" use="optional"/>
  </xs:complexType>
  <xs:complexType name="yukie_storeType">
    <xs:sequence>
      <xs:element type="navigationType" name="navigation"/>
      <xs:element type="body_advertisementType" name="body_advertisement"/>
      <xs:element type="motto_1Type" name="motto_1"/>
      <xs:element type="xs:string" name="motto_2"/>
      <xs:element type="xs:string" name="rectangle"/>
      <xs:element type="xs:string" name="rectangle_line"/>
      <xs:element type="xs:string" name="rectangle_content"/>
      <xs:element type="xs:string" name="popular"/>
      <xs:element type="xs:string" name="r"/>
      <xs:element type="xs:string" name="sort_by"/>
      <xs:element type="store_detailsType" name="store_details"/>
      <xs:element type="card_propertiesType" name="card_properties"/>
      <xs:element type="xs:string" name="logo_footer"/>
      <xs:element type="xs:string" name="copyright_footer"/>
      <xs:element type="xs:string" name="facebook_footer"/>
      <xs:element type="xs:string" name="instagram_footer"/>
      <xs:element type="xs:string" name="line"/>
      <xs:element type="xs:string" name="twitter_footer"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="categoryType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="xs:string" name="validity" minOccurs="0"/>
      <xs:element type="xs:short" name="price" minOccurs="0"/>
      <xs:element type="xs:string" name="rating" minOccurs="0"/>
      <xs:element type="xs:float" name="number_of_user" minOccurs="0"/>
      <xs:element type="xs:int" name="voucher_value"/>
      <xs:element type="xs:string" name="description" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="customer_type" use="optional"/>
  </xs:complexType>
  <xs:complexType name="card_propertiesType">
    <xs:sequence>
      <xs:element type="cardType" name="card" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="delivery_periodType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="maximum_time" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="voucher_forType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="where" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="motto_1Type" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="p"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="voucher_onlineType">
    <xs:sequence>
      <xs:element type="voucher_forType" name="voucher_for"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="adsType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="img"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="body_advertisementType">
    <xs:sequence>
      <xs:element type="adsType" name="ads"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="store_detailsType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="storeType" name="store" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="numberType" name="number"/>
      <xs:element type="xs:anyURI" name="website_address"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="logoType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="img"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="navigationType">
    <xs:sequence>
      <xs:element type="logoType" name="logo"/>
      <xs:element type="xs:string" name="homelink"/>
      <xs:element type="xs:string" name="storelink"/>
      <xs:element type="xs:string" name="contactlink"/>
      <xs:element type="xs:string" name="searchbox"/>
      <xs:element type="xs:string" name="searchcontent"/>
      <xs:element type="xs:string" name="signuplink"/>
      <xs:element type="xs:string" name="signinlink"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="delivery_costType">
    <xs:sequence>
      <xs:element type="delivery_areaType" name="delivery_area"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="for" use="optional"/>
  </xs:complexType>
  <xs:complexType name="delivery_period1Type">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="minimum_time" use="optional"/>
        <xs:attribute type="xs:string" name="minimum_type" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="delivery_areaType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="distance" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== YoAashutosh/Yukie-Gift-Card-Store/Development/catalog_20048803.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="catalog_20048803.css"?>
<!--
    Name: Aashutosh Sharma
    londonmetID: 20048803
    collegeID: np01cp4s210087
    description
-->

<yukie_store xsi:noNamespaceSchemaLocation="catalog_20048803.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <navigation>
        <logo img="yukie"/>
        <homelink> HOME </homelink>
        <storelink> STORE </storelink>
        <contactlink> CONTACT </contactlink>
        <searchbox/>
        <searchcontent>Search Your Card</searchcontent>
        <signuplink> SIGN UP </signuplink>
        <signinlink> LOGIN </signinlink>   
    </navigation>
    <body_advertisement>
        <ads img="aash"/>
    </body_advertisement>
    <motto_1>Our Shop is Gift To <p>You All</p></motto_1>
    <motto_2>Your relationship needs something more.</motto_2>
    <rectangle/>
    <rectangle_line/>
    <rectangle_content>Get Your Card</rectangle_content>
    <popular>Most Popular Cards</popular>
    <r/>
    <sort_by>Sort By ↓</sort_by>
    <store_details>
        <name>YUKIE</name>
        <store online="Online">Online Store</store>        
        <store physical="Physical">Physical Store
            <time_opening>Store Opens At: 10:00 AM</time_opening>
            <time_closing>Store Closes At:  6:00 PM</time_closing>
            <location>Location: 5th Street,3rd Block East,London</location>
        </store>
        <number>
            <mobile_number>Mobile Number: 9876543210</mobile_number>
            <telephone_number>Telephone: 0123456</telephone_number>
        </number>
        <website_address>www.yukie12@gmail.com</website_address>
    </store_details>
    <card_properties>
        <card kind="Online" C_id="C001">
            <cardImg img="itunes"/>
            <category customer_type="VIP">
                <name>Itunes Card</name>
                <validity>3 years</validity>
                <price>5000</price>
                <rating>⭐️⭐️⭐️⭐️</rating>
                <number_of_user>2 </number_of_user>
                <voucher_value>10000</voucher_value>
            </category>
            <voucher_online>
                    <voucher_for where="Other">Itunes</voucher_for>
            </voucher_online>
        </card>
        <card kind="Online" C_id="C002">
            <cardImg img="amazon"/>
            <category customer_type="MEDIUM">
                <name>Love</name>
                <price>1500</price>
                <rating>⭐️⭐️⭐️</rating>
                <number_of_user>5 </number_of_user>
                <voucher_value>25000</voucher_value>
                <description>Lorem Ipsum </description>
            </category>
            <voucher_online>
                    <voucher_for where="Other">Amazon</voucher_for>
            </voucher_online>
        </card>
        <card kind="Online" C_id="C003">
            <cardImg img="googleplay"/>
            <category customer_type="NORMAL">
                <name>Naruto</name>
                <validity>6 months</validity>
                <price>1000</price>
                <voucher_value>10000</voucher_value>
                <description>Lorem Ipsum </description>
            </category>
            <voucher_online>
                    <voucher_for where="Other">Googleplay</voucher_for>
            </voucher_online>
        </card>
        <card kind="Online" C_id="C004">
            <cardImg img="gastation"/>
            <category customer_type="NORMAL">
                <name>Kakashi</name>
                <validity>6 months</validity>
                <price>2000</price>
                <rating>⭐️⭐️</rating>
                <voucher_value>10000</voucher_value>
            </category>
            <voucher_online>
                    <voucher_for where="Gas _Station">Other</voucher_for>
            </voucher_online>
        </card>
        <card kind="Online" C_id="C005">
            <cardImg img="jewellery"/>
            <category customer_type="NORMAL">
                <name>Itachi</name>
                <validity>6 months</validity>
                <price>3000</price>
                <rating>⭐️⭐️</rating>
                <voucher_value>10000</voucher_value>
            </category>
            <voucher_online>
                    <voucher_for where="Jewllery">Jewellery Shop</voucher_for>
            </voucher_online>
        </card>
        <card kind="Physical" C_id="C006">
            <cardImg img="netflix"/>
            <category customer_type="MEDIUM">
                <name>Hinata</name>
                <price>1000</price>
                <rating>⭐️⭐️</rating>
                <number_of_user>15</number_of_user>
                <voucher_value>15000</voucher_value>
                <description>Lorem Ipsum </description>
            </category>
            <voucher_physical>
                    <voucher_for where="Other">Netflix</voucher_for>
            </voucher_physical> 
            <delivery type="International">
                <delivery_period maximum_time="maximum">7 days</delivery_period>
                <delivery_period1 minimum_time="minimum">3 days</delivery_period1>
            </delivery>
            <delivery_charge>
                    <delivery_means by_air="Aeroplane">Rs 3000</delivery_means>
            </delivery_charge>
        </card>
        <card kind="Physical" C_id="C007">
            <cardImg img="paypal"/>
            <category customer_type="VIP">
                <name>Ichi</name>
                <validity>3 years</validity>
                <price>5000</price>
                <rating>⭐️⭐️⭐️⭐️</rating>
                <voucher_value>100000</voucher_value>
                <description>Lorem Ipsum</description>
            </category>
            <voucher_physical>
                    <voucher_for where="Other">Paypal</voucher_for>
            </voucher_physical>
            <delivery type="National">
                <delivery_period maximum_time="max">2 days</delivery_period>
                <delivery_period1 minimum_type="min">1 day</delivery_period1>
            </delivery> 
            <delivery_charge>
                    <delivery_means by_train="Train">Rs 1500</delivery_means>
            </delivery_charge>
        </card>
        <card kind="Physical" C_id="C007">
            <cardImg img="restaurant"/>
            <category customer_type="HIGH">
                <name>Platinum</name>
                <validity>2 years</validity>
                <price>3000</price>
                <rating>⭐️⭐️⭐️</rating>
                <voucher_value>80000</voucher_value>
                <description>Lorem Ipsum </description>
            </category>
            <voucher_physical>
                    <voucher_for where="Restaurant">Restaurant</voucher_for>
            </voucher_physical> 
            <delivery type="National">
                <delivery_period maximum_time="max">2 days</delivery_period>
                <delivery_period1 minimum_type="min">1 day</delivery_period1>
            </delivery>
            <delivery_charge>
                    <delivery_means by_road="Road">
                        <delivery_cost for="Bike_Delivery">
                            <delivery_area distance="More_than_10KM">Rs 1500</delivery_area> 
                        </delivery_cost>
                    </delivery_means>
            </delivery_charge>
        </card>
        <card kind="Physical" C_id="C008">
            <cardImg img="retail"/>
            <category customer_type="HIGH">
                <name>Gold</name>
                <validity>1.5 years</validity>
                <price>2500</price>
                <rating>⭐️⭐️⭐️</rating>
                <voucher_value>50000</voucher_value>
                <description>Lorem Ipsum </description>
            </category>
            <voucher_physical>
                    <voucher_for where="Retail_Store">Retail Store</voucher_for>
            </voucher_physical> 
            <delivery type="National">
                <delivery_period maximum_time="max">2 days</delivery_period>
                <delivery_period1 minimum_type="min">1 day</delivery_period1>
            </delivery>
            <delivery_charge>
                    <delivery_means by_road="Road">
                        <delivery_cost for="Bus_Delivery">
                            <delivery_area distance="Less_than_3KM">Rs 500</delivery_area>
                        </delivery_cost>
                    </delivery_means>      
            </delivery_charge>    
        </card>
        <card kind="Physical" C_id="C009">
            <cardImg img="spotify"/>
            <category customer_type="MEDIUM">
                <name>Silver</name>
                <validity>1 year</validity>
                <price>5000</price>
                <voucher_value>25000</voucher_value>
            </category>
            <voucher_physical>   
                    <voucher_for where="Other">Spotify</voucher_for>
            </voucher_physical>    
            <delivery type="National">
                <delivery_period maximum_time="max">2 days</delivery_period>
                <delivery_period1 minimum_type="min">1 day</delivery_period1>
            </delivery>
            <delivery_charge>
                    <delivery_means by_road="Road">
                        <delivery_cost for="Bus_Delivery">
                            <delivery_area distance="Less_than_3KM">Rs 500</delivery_area>
                        </delivery_cost>
                    </delivery_means>
            </delivery_charge>
        </card>
        <card kind="Physical" C_id="C010">
            <cardImg img="starbucks"/>
            <category customer_type="NORMAL">
                <name>Madara</name>
                <validity>6 months</validity>
                <voucher_value>10000</voucher_value>
                <description>Lorem Ipsum</description>
            </category>
            <voucher_physical>
